version: '3.3'
services:
  app:
    image: app:latest
    container_name: apppy
    ports:
      - 5000:5000
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000